trigger: 
  branches:
    include:
      - "azure-pipelines"

variables: 
  ACR_NAME: 'IvoyantACR'
  ACR_RESOURCE_GROUP: 'Ivoyant-ACR'
  DOCKERFILE_PATH_UI: './cc-ui/Dockerfile'
  DOCKERFILE_PATH_API: './CC_api/Dockerfile'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Images'
    jobs:
      - job: Build_UI
        displayName: 'Build UI Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build UI Docker Image'
            inputs:
              containerRegistry: 'containerregistry-ui'
              repository: '$(ACR_NAME)/ui'
              command: 'build'
              Dockerfile: '$(DOCKERFILE_PATH_UI)'
              tags: '$(Build.BuildId)'

      - job: Build_API
        displayName: 'Build API Docker Image'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: Docker@2
            displayName: 'Build API Docker Image'
            inputs:
              containerRegistry: 'containerregistry-api'
              repository: '$(ACR_NAME)/api'
              command: 'build'
              Dockerfile: '$(DOCKERFILE_PATH_API)'
              tags: '$(Build.BuildId)'         